configVersion: "1.0"

# Profile
name: "Harshit Mani Tripathi"
subtitle: "Aspiring DevOps Engineer, Homelab enthusiast, Developer"
# description: |
#   aka @ironicbadger
#   Father. Educator. Tinkerer.
avatar: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407361/cropped_circle_image_pz7ua1.png"
favicon: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407384/favicon_josj9j.ico"

## Analytics
analytics:
  google:
    id: "G-MSTPBLQLXE"
  goatcounter:
    id: "hudater-linkme"
    selfhosted: false
  plausible:
    domain: "" # tracked site
    script_url: ""


# Theme selection
theme: "default"

# Background options
# type: color | image | gradient | particles
background:
  type: "color"
  value: "#1e1f26"

# Main links (large buttons)
# icon: Simple Icons slug (see https://simpleicons.org)
# color: hex color for button background
links:

  - title: "GitHub: Hudater"
    url: "https://github.com/Hudater"
    icon: "github"
    color: "#0a0a0a"

  - title: "Personal Tech Blog"
    url: "https://blog.hudater.dev"
    icon: "rss"
    color: "#404040"

  - title: "Technical Docs"
    url: "https://docs.hudater.dev"
    icon: "github"
    color: "#8CA1AF"

# Sections with headings
sections:
  - title: "Projects"
    links:
      - title: "My Homelab!"
        url: "https://blog.hudater.dev/posts/homelab/"
        iconUrl: "assets/icons/selfhosted.png"
        color: "#ee7125"
      - title: "Automated Infrastructure"
        url: "https://github.com/hudater/infra_lab/"
        icon: "opentofu"
        # color: "#FFDA18"
      - title: "Cohort Assignments and Blogs"
        url: "https://cohort.hudater.dev/"
        icon: "rss"
        color: "#EF6C00"

# Social links (small icons)
socials:
  - icon: "gmail"
    url: "mailto:harshit@hudater.dev"
    color: "#EA4335"
  - icon: "x"
    url: "https://twitter.com/hudater_"
    color: "#FFFFFF"
  - icon: "reddit"
    url: "https://www.reddit.com/user/hudater"
    color: "#FF4500"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/hudater"
    color: "#005FF9"
