configVersion: "1.0"

# Profile
name: "Harshit Mani Tripathi"
subtitle: "Aspiring DevOps Engineer, Homelab enthusiast, Developer"
# description: |
#   aka @ironicbadger
#   Father. Educator. Tinkerer.
avatar: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407361/cropped_circle_image_pz7ua1.png"
favicon: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407384/favicon_josj9j.ico"

## Analytics
analytics:
  google:
    #id: "G-TEST123"
  goatcounter:
    #id: "test-goat"


# Theme selection
theme: "default"

# Background options
# type: color | image | gradient | particles
background:
  type: "color"
  value: "#1e1f26"

# Main links (large buttons)
# icon: Simple Icons slug (see https://simpleicons.org)
# color: hex color for button background
links:
  - title: "Personal Blog"
    url: "https://blog.hudater.dev"
    icon: "rss"
    color: "#404040"

  - title: "GitHub: Ironicbadger"
    url: "https://github.com/Hudater"
    icon: "github"
    color: "#0a0a0a"

  - title: "Technical Docs"
    url: "https://docs.hudater.dev"
    icon: "github"
    color: "#8CA1AF"

  - title: "YouTube: Personal Stuff"
    url: "https://www.youtube.com/@alexkretzschmar"
    icon: "youtube"
    color: "#dc2626"

# Sections with headings
sections:
  - title: "Projects"
    links:
      - title: "My Homelab!"
        url: "https://selfhosted.show"
        iconUrl: "assets/icons/selfhosted.png"
        color: "#ee7125"
      - title: "linuxserver.io - Co-founder"
        url: "https://linuxserver.io"
        iconUrl: "assets/icons/linuxserver.png"
        color: "#DA3B8A"

# Social links (small icons)
socials:
  - icon: "gmail"
    url: "mailto:harshit@hudater.dev"
    # color: "#6364FF"
  - icon: "x"
    url: "https://twitter.com/hudater_"
    color: "#FFFFFF"
  # - icon: "reddit"
  #   url: "https://www.reddit.com/user/Ironicbadger"
  #   color: "#FF4500"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/hudater"
    color: "#0A66C2"
